import type { ReactElement } from 'react';
import type { LayoutProps } from 'TYPES/next';

import './globals.css';

// * ---------------------------------------------------------------------- * //

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

// -------------------------------------------------------------------------- //

function RootLayout({ children }: LayoutProps): ReactElement {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}

// * ---------------------------------------------------------------------- * //

export default RootLayout;
